export const wicons = {
    "01d": "wicons/sun.png",
    "01n": "wicons/moon.png",
    "02d": "wicons/sun+cloud.png",
    "02n": "wicons/moon+cloud.png",
    "03d": "wicons/sun+cloud.png",
    "03n": "wicons/moon+cloud.png",
    "04d": "wicons/clouds.png",
    "04n": "wicons/clouds.png",
    "09d": "wicons/heavy rain.png",
    "09n": "wicons/heavy rain.png",
    "10d": "wicons/sun+rain.png",
    "10n": "wicons/moon+rain.png",
    "11d": "wicons/rain+thunder.png",
    "11n": "wicons/rain+thunder.png",
    "13d": "wicons/snow.png",
    "13n": "wicons/snow.png",
    "50d": "wicons/cloud+haze.png",
    "50n": "wicons/cloud+haze.png"
}
